server:
  port: 9999

logging:
  level:
    org.springframework.cloud.gateway: ERROR
    org.springframework.http.server.reactive: ERROR
    org.springframework.web.reactive: ERROR
    reactor.ipc.netty: ERROR
    reactor.netty: ERROR

services:
  users: http://192.168.56.116:8080
  concepts: http://192.168.56.117:8080